name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.4
          
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      
      # 保存 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
      # 保存 App Bundle
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab
